# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "GYMPY: Combining OpenAI Gym with GPy for Robotic Control"
email: jcpetangoda1@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  This blog will detail a part of my (Janith's) journey through applying GP based machine learning techniques to the control of motile robots, starting with the robotic arm.
url: "http://gympy.org"
twitter_username: janith_pet
github_username:  janithPet

# Build settings
markdown: kramdown
theme: minima
gems:
  -jekyll-coffeescript
  -jekyll-paginate
  - jekyll-feed
  - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock
